import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://www.foundingspirits.com/wp-content/uploads/2021/04/FS_Vodka_Square_Transparent_01_KF-768x768.png",
    title: "Craft Vodka",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "$40",
    newPrice: "36",
    company: "Founding Spirits",
    color: "blue",
    category: "spirits",
  },
  {
    img: "https://www.foundingspirits.com/wp-content/uploads/2023/09/navyrum.png",
    title: "Navy Strength Rum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(10 reviews)",
    prevPrice: "$52",
    newPrice: "38",
    company: "Founding Spirits",
    color: "red",
    category: "spirits",
  },

  {
    img: "https://www.foundingspirits.com/wp-content/uploads/2022/03/rye-768x768.png",
    title: "RYE Whiskey",
    star: <AiFillStar className="rating-star" />,
    reviews: "(8 reviews)",
    prevPrice: "$40",
    newPrice: "38",
    company: "Founding Spirits",
    color: "red",
    category: "spirits",
  },
  {
    img: "https://www.foundingspirits.com/wp-content/uploads/2023/10/bourbon.png",
    title: "Bourbon Whiskey",
    star: <AiFillStar className="rating-star" />,
    reviews: "(15 reviews)",
    prevPrice: "$49",
    newPrice: "43",
    company: "Founding Spirits",
    color: "yellow",
    category: "spirits",
  },
  {
    img: "https://www.foundingspirits.com/wp-content/uploads/2023/09/whiterum.png",
    title: "White Rum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3 reviews)",
    prevPrice: "$45",
    newPrice: "38",
    company: "Founding Spirits",
    color: "white",
    category: "spirits",
  },
  {
    img: "https://www.foundingspirits.com/wp-content/uploads/2021/04/FS_Gin_Square_Transparent_01_KF-768x768.png",
    title: "Dry Gin",
    star: <AiFillStar className="rating-star" />,
    reviews: "(5 reviews)",
    prevPrice: "$39",
    newPrice: "38",
    company: "Founding Spirits",
    color: "green",
    category: "spirits",
  },

  {
    img: "https://www.stillspirits.com/cdn/shop/files/Vodka_Spirit_Flavouring_fbec87a1-f674-4c2b-abb7-65b7f8aa35ad.jpg?v=1685330987&width=840",
    title: "Vodka Spirit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(10 reviews)",
    prevPrice: "$23",
    newPrice: "19",
    company: "Still Spirits",
    color: "Blue",
    category: "spirits",
  },

  {
    img: "https://www.stillspirits.com/cdn/shop/files/Coconut_Rum_Liqueur_Flavouring.jpg?v=1690503346&width=840",
    title: "Coconut Rum Spirit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(17 reviews)",
    prevPrice: "$32",
    newPrice: "29",
    company: "Still Spirits",
    color: "white",
    category: "spirits",
  },

  {
    img: "https://www.stillspirits.com/cdn/shop/files/Jamaican_Dark_Rum_Spirit_Flavouring_78a97650-f079-4d48-a86c-0c371a7746e9.jpg?v=1686262621&width=840",
    title: "Jamaican Dark Rum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(6 reviews)",
    prevPrice: "$43",
    newPrice: "38",
    company: "Still Spirits",
    color: "black",
    category: "spirits",
  },

  {
    img: "https://www.stillspirits.com/cdn/shop/files/Spiced_Dark_Rum_Spirit_Flavouring_9c5bac5c-f82c-4ea7-a0ca-ecbd0273332d.jpg?v=1685330341&width=840",
    title: "Dark Spiced Rum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(2 reviews)",
    prevPrice: "$35",
    newPrice: "28",
    company: "Still Spirits",
    color: "black",
    category: "spirits",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2024/10/Christmas12UKNewWheel251024.jpg",
    title: "12 Beers of Christmas",
    star: <AiFillStar className="rating-star" />,
    reviews: "(10 reviews)",
    prevPrice: "$42",
    newPrice: "40",
    company: "Beers of Europe",
    color: "all",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2024/05/8SailImperialPorter330ml-450x450.jpg",
    title: "8 Sail Imperial Porter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3 reviews)",
    prevPrice: "$9",
    newPrice: "7",
    company: "Beers of Europe",
    color: "black",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2024/06/8SailNo14-450x450.jpg",
    title: "8 Sail No14 Barley",
    star: <AiFillStar className="rating-star" />,
    reviews: "(15 reviews)",
    prevPrice: "$14",
    newPrice: "12",
    company: "Beers of Europe",
    color: "black",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2023/12/BiddendenGribbleBridgeWhite-450x450.jpg",
    title: "B.Gribble Bridge",
    star: <AiFillStar className="rating-star" />,
    reviews: "(12 reviews)",
    prevPrice: "$18",
    newPrice: "15",
    company: "Beers of Europe",
    color: "green",
    category: "beer",
  },

  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2024/05/ConghamPhoenixCV-450x450.jpg",
    title: "Congham Phoenix CV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1 reviews)",
    prevPrice: "$14",
    newPrice: "13",
    company: "Beers of Europe",
    color: "yellow",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2023/04/LindisfarneCherryWine-300x300.jpg",
    title: "Lindisfarne Cherry Wine",
    star: <AiFillStar className="rating-star" />,
    reviews: "(10 reviews)",
    prevPrice: "$10",
    newPrice: "9",
    company: "Beers of Europe",
    color: "red",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2023/04/LymeBayGingerWine-300x300.jpg",
    title: "Lyme Bay Ginger Wine",
    star: <AiFillStar className="rating-star" />,
    reviews: "(20 reviews)",
    prevPrice: "$17",
    newPrice: "15",
    company: "Beers of Europe",
    color: "yellow",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2023/04/LymeBaySandbar-300x300.jpg",
    title: "Lyme Bay Sandbar",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "$15",
    newPrice: "13",
    company: "Beers of Europe",
    color: "green",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2023/04/CelticMarchesJacobMarleysMulledWine-300x300.jpg",
    title: "CMJ Marleys Mulled",
    star: <AiFillStar className="rating-star" />,
    reviews: "(21 reviews)",
    prevPrice: "$7",
    newPrice: "6",
    company: "Beers of Europe",
    color: "black",
    category: "beer",
  },
  {
    img: "https://www.beersofeurope.co.uk/wp-content/uploads/2023/10/ConghamWhiteBrut-1-450x450.jpg",
    title: "Congham Sparkling Brut",
    star: <AiFillStar className="rating-star" />,
    reviews: "(30 reviews)",
    prevPrice: "$30",
    newPrice: "26",
    company: "Beers of Europe",
    color: "black",
    category: "beer",
  },
  {
    img: "https://m.media-amazon.com/images/I/81Kv3XB26yL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Coca-Cola 24 x 500ml",
    star: <AiFillStar className="rating-star" />,
    reviews: "(32 reviews)",
    prevPrice: "$28",
    newPrice: "26",
    company: "amazon",
    color: "red",
    category: "softdrinks",
  },
  {
    img: "https://m.media-amazon.com/images/I/716w+zkY21L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Red Bull 12 x 250ml",
    star: <AiFillStar className="rating-star" />,
    reviews: "(28 reviews)",
    prevPrice: "$20",
    newPrice: "18",
    company: "amazon",
    color: "blue",
    category: "softdrinks",
  },
  {
    img: "https://m.media-amazon.com/images/I/61+vmaLbltL._AC_UL480_FMwebp_QL65_.jpg",
    title: "G Tropical Lemonade",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "$3",
    newPrice: "2",
    company: "amazon",
    color: "blue",
    category: "softdrinks",
  },

  {
    img: "https://m.media-amazon.com/images/I/61L3ECNIjpL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Fanta Fruit 2L",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "$4",
    newPrice: "2.5",
    company: "amazon",
    color: "red",
    category: "softdrinks",
  },
  {
    img: "https://m.media-amazon.com/images/I/51YE9jpScRL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Pepsi",
    star: <AiFillStar className="rating-star" />,
    reviews: "(35 reviews)",
    prevPrice: "$2",
    newPrice: "1.80",
    company: "amazon",
    color: "black",
    category: "softdrinks",
  },
  {
    img: "https://m.media-amazon.com/images/I/61DA2elZvLL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Fanta Pineapple",
    star: <AiFillStar className="rating-star" />,
    reviews: "(10 reviews)",
    prevPrice: "$3",
    newPrice: "2.10",
    company: "amazon",
    color: "yellow",
    category: "softdrinks",
  },
  {
    img: "https://m.media-amazon.com/images/I/816AodaDmeL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Walkers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "$5",
    newPrice: "4.63",
    company: "amazon",
    color: "green",
    category: "crisps",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Bk9fbK-TL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Morrisons",
    star: <AiFillStar className="rating-star" />,
    reviews: "(25 reviews)",
    prevPrice: "$4",
    newPrice: "3.10",
    company: "amazon",
    color: "red",
    category: "crisps",
  },
  {
    img: "https://m.media-amazon.com/images/I/71NsTHeHWVL._AC_UL480_FMwebp_QL65_.jpg",
    title: "SERIOUS PIG Sausage",
    star: <AiFillStar className="rating-star" />,
    reviews: "(5 reviews)",
    prevPrice: "$18",
    newPrice: "16.80",
    company: "amazon",
    color: "black",
    category: "crisps",
  },
  {
    img: "https://m.media-amazon.com/images/I/61hpXTItRvL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Quavers Snacks Cheese",
    star: <AiFillStar className="rating-star" />,
    reviews: "(15 reviews)",
    prevPrice: "$5",
    newPrice: "3",
    company: "amazon",
    color: "yellow",
    category: "crisps",
  },
  {
    img: "https://m.media-amazon.com/images/I/51i8gjOU0oL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Pringles",
    star: <AiFillStar className="rating-star" />,
    reviews: "(12 reviews)",
    prevPrice: "$2.5",
    newPrice: "1.85",
    company: "amazon",
    color: "green",
    category: "crisps",
  },
  {
    img: "https://m.media-amazon.com/images/I/71XtJ5UW31L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Chipsticks Salt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(20 reviews)",
    prevPrice: "$2",
    newPrice: "1.25",
    company: "amazon",
    color: "blue",
    category: "crisps",
  },
];

export default data;